name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
 
trigger: none
 
pr: none
 
stages :        
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
              - checkout: self
 
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'ARM_Template_DevOps_SPN'
                  subscriptionId: '2daf7420-f7f4-4e0f-8a65-8dd8f147545b'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'tamops-arm-template'
                  location: 'eastus2'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.DefaultWorkingDirectory)/vnet.json'
                  csmParametersFile: '$(System.DefaultWorkingDirectory)/vnet.parameters.json'
                  deploymentMode: 'Incremental'